export const TILES = {
  grass: {
    emoji: '🟩', walkable: true, encounter: true, description: 'Field — wild monsters may appear',
    variants: ['🟩', '🟩', '🟩', '🟩', '🍀', '🌼'],
  },
  tree: { emoji: '🌲', walkable: false, encounter: false, description: 'Tree — blocks the way' },
  water: { emoji: '🟦', walkable: false, encounter: false, description: 'Water — blocks the way' },
  townEntrance: { emoji: '🏘️', walkable: true, encounter: false, action: 'enterTown', description: 'Town — shop, smith, and quest board' },
  dungeonEntrance: { emoji: '🕳️', walkable: true, encounter: false, action: 'enterDungeon', description: 'Dungeon — the way to the boss' },
  shop: { emoji: '🏪', walkable: true, encounter: false, action: 'enterShop', description: 'Shop — buy and sell gear' },
  smith: { emoji: '⚒️', walkable: true, encounter: false, action: 'enterSmith', description: 'Smith — upgrade your equipment' },
  exit: { emoji: '🚪', walkable: true, encounter: false, action: 'exitMap', description: 'Door — leave this area' },
  boss: { emoji: '🐉', walkable: true, encounter: false, action: 'bossBattle', description: 'The dragon awaits' },
  caveFloor: { emoji: '⬛', walkable: true, encounter: true, description: 'Cave floor — wild monsters may appear' },
  caveWall: { emoji: '🪨', walkable: false, encounter: false, description: 'Cave wall — blocks the way' },
  cavePool: { emoji: '💧', walkable: false, encounter: false, description: 'Underground pool — blocks the way' },
  miniDungeonEntrance: { emoji: '🪜', walkable: true, encounter: false, action: 'exitMiniDungeon', description: 'Ladder — climb back to the surface' },
  miniDungeonTreasure: { emoji: '💰', walkable: true, encounter: false, action: 'collectTreasure', description: 'Treasure — step here to collect it' },
  questBoard: { emoji: '📋', walkable: true, encounter: false, action: 'enterQuestBoard', description: 'Quest Board — turn in completed quests' },
  well: { emoji: '⛲', walkable: true, encounter: false, action: 'useWell', description: 'Well — rest here to fully heal, free' },
  mountain: { emoji: '⛰️', walkable: false, encounter: false, requiresTool: 'miningPick', description: 'Mountain — needs a mining pick to clear' },
  mountainCache: { emoji: '⛰️', walkable: false, encounter: false, requiresTool: 'miningPick', hasReward: true, description: 'Mountain — needs a mining pick to clear' },
  thicket: { emoji: '🌳', walkable: false, encounter: false, requiresTool: 'axe', description: 'Thicket — needs an axe to clear' },
  thicketCache: { emoji: '🌳', walkable: false, encounter: false, requiresTool: 'axe', hasReward: true, description: 'Thicket — needs an axe to clear' },
};
