export const TILES = {
  grass: { emoji: '🟩', walkable: true, encounter: true },
  tree: { emoji: '🌲', walkable: false, encounter: false },
  water: { emoji: '🟦', walkable: false, encounter: false },
  townEntrance: { emoji: '🏘️', walkable: true, encounter: false, action: 'enterTown' },
  dungeonEntrance: { emoji: '🕳️', walkable: true, encounter: false, action: 'enterDungeon' },
  shop: { emoji: '🏪', walkable: true, encounter: false, action: 'enterShop' },
  smith: { emoji: '⚒️', walkable: true, encounter: false, action: 'enterSmith' },
  exit: { emoji: '🚪', walkable: true, encounter: false, action: 'exitMap' },
  boss: { emoji: '🐉', walkable: true, encounter: false, action: 'bossBattle' },
  caveFloor: { emoji: '⬛', walkable: true, encounter: true },
  caveWall: { emoji: '🪨', walkable: false, encounter: false },
  cavePool: { emoji: '💧', walkable: false, encounter: false },
  miniDungeonEntrance: { emoji: '🪜', walkable: true, encounter: false, action: 'exitMiniDungeon' },
  miniDungeonTreasure: { emoji: '💰', walkable: true, encounter: false, action: 'collectTreasure' },
  questBoard: { emoji: '📋', walkable: true, encounter: false, action: 'enterQuestBoard' },
  mountain: { emoji: '⛰️', walkable: false, encounter: false, requiresTool: 'miningPick' },
  mountainCache: { emoji: '⛰️', walkable: false, encounter: false, requiresTool: 'miningPick', hasReward: true },
  thicket: { emoji: '🌳', walkable: false, encounter: false, requiresTool: 'axe' },
  thicketCache: { emoji: '🌳', walkable: false, encounter: false, requiresTool: 'axe', hasReward: true },
};
